-- copy_generated_inorganics_to_clipboard.lua
-- SWD
-- a quick hack to copy game-generated inorganic materials to the windows clipboard.  Obviously.

local world = df.global.world

local output = ""
local matches = 0

local searchterm = "[GENERATED]"
--local searchterm = "STEEL"
--local searchterm = "IRON"	-- also matches PIG_IRON and ENVIRONMENT.
--local searchterm = ":IRON"
--local searchterm = "[ITEMS_METAL]"
searchterm = searchterm:escape_pattern()  -- escape_pattern() is a dfhack string extension.


local translateName = dfhack.TranslateName or dfhack.translation.translateName


---@param ... string
local function add_output(...)
    local t = {...}
    table.insert(t, "")		-- appending this basically adds a \n to the real last string.
				-- see Programming in Lua (first edition) 11.6 – String Buffers
				-- https://www.lua.org/pil/11.6.html
    output = output .. table.concat(t, "\n")
end


add_output(
	"This is the generated inorganic materials raws for a Dwarf Fortess world:",
	string.format("%s (%s)",
		translateName(world.world_data.name, false),
		translateName(world.world_data.name, true)
	),
	string.format("This world was generated by Dwarf Fortress version 0.%s", world.worldgen.version),
	"",
	""
)


-- inspect all inorganic materials to see which are auto-generated.
for _,mat in ipairs(world.raws.inorganics.all) do
    local t = {}
    t[1] = string.format("[INORGANIC:%s]", mat.id)
    for i,s in ipairs(mat.str) do
	t[i+2] = s.value
    end
    table.insert(t, "")    -- blank line

    local joined = table.concat(t, "\n")

    -- I wish we had 0-widths like grep's \b that matches a boundary between a word char and a non-word char.
    if string.find(joined, searchterm) then
	add_output(joined)
	matches = matches + 1
    end
end


print(string.format("%d match%s.", matches, (matches == 1 and '' or 'es') ))
print("Setting system clipboard; this may take a long time.")
dfhack.internal.setClipboardTextCp437Multiline(output)
-- unfortunately, our output is in UTF-8, not in CP437.
-- happily, ASCII characters map without a problem.
-- we just hope that there aren't any non-ASCII characters.